#!/bin/bash
# Installs claude-state-agent on this machine. Idempotent.
#
# Generates a per-machine shared token on first run, stored in
# `$INSTALL_DIR/state-agent.env` (mode 0600). The systemd unit sources this file
# so the token reaches the running process via `CLAUDE_FLEET_STATE_TOKEN`.
#
# Uses uv (auto-installed if missing) — uv bundles its own Python, robust across
# the heterogeneous fleet (no python3.X-venv apt hassle).
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SKILL_DIR"

INSTALL_USER="${SUDO_USER:-${USER:-$(id -un)}}"
INSTALL_HOME="$(getent passwd "$INSTALL_USER" | cut -d: -f6)"
INSTALL_HOME="${INSTALL_HOME:-$HOME}"
INSTALL_DIR="${INSTALL_DIR:-$INSTALL_HOME/.claude-fleet-starter}"
mkdir -p "$INSTALL_DIR"

# 0. Ensure uv is available (per-user install path).
UV_BIN=""
for cand in "$INSTALL_HOME/.local/bin/uv" /usr/local/bin/uv "$(command -v uv 2>/dev/null || true)"; do
    if [[ -n "$cand" && -x "$cand" ]]; then UV_BIN="$cand"; break; fi
done
if [[ -z "$UV_BIN" ]]; then
    echo "Installing uv..."
    curl -fsSL https://astral.sh/uv/install.sh | sh 2>&1 | tail -2
    UV_BIN="$INSTALL_HOME/.local/bin/uv"
fi
echo "✓ uv: $UV_BIN"

# 1. Create venv + install deps via uv.
"$UV_BIN" venv --python 3.12 .venv 2>&1 | tail -1
"$UV_BIN" pip install --python .venv/bin/python \
    fastapi "uvicorn[standard]" pydantic httpx 2>&1 | tail -2
echo "✓ dépendances installées"

# 2. Generate or reuse the shared token.
TOKEN_FILE="$INSTALL_DIR/state-agent.env"
if [[ -f "$TOKEN_FILE" ]] && grep -q "^CLAUDE_FLEET_STATE_TOKEN=" "$TOKEN_FILE"; then
    echo "✓ token already provisioned at $TOKEN_FILE"
else
    TOKEN="$(head -c 32 /dev/urandom | base64 | tr -d '=+/' | head -c 40)"
    umask 077
    cat >"$TOKEN_FILE" <<EOF
# claude-state-agent shared token (auto-generated by install.sh).
# Sourced by the systemd unit. Treat as a password — required for /action,
# /sessions/*/inject, /claude/start and similar mutation endpoints.
CLAUDE_FLEET_STATE_TOKEN=$TOKEN

# Bind: loopback (default, safe), tailnet (opt-in), or 0.0.0.0 (discouraged).
CLAUDE_FLEET_BIND=loopback

# Opt-in to the "accept_all" remote action (= "Yes, don't ask again" pressed
# remotely without a human in the loop). Off by default.
# CLAUDE_FLEET_ALLOW_ACCEPT_ALL=0
EOF
    chmod 600 "$TOKEN_FILE"
    chown "$INSTALL_USER:$INSTALL_USER" "$TOKEN_FILE" 2>/dev/null || true
    echo "✓ token généré → $TOKEN_FILE (mode 0600)"
    echo "  Garde-le pour configurer un agrégateur central qui poll cette machine."
fi

# 3. Render the systemd unit (substitute the placeholders).
UNIT_SRC="$SKILL_DIR/systemd/claude-state-agent.service"
UNIT_DST="/etc/systemd/system/claude-state-agent.service"
if command -v sudo >/dev/null 2>&1 && [[ $EUID -ne 0 ]]; then
    SUDO="sudo"
else
    SUDO=""
fi
TMP_UNIT="$(mktemp)"
sed \
    -e "s#__USER__#${INSTALL_USER}#g" \
    -e "s#__SKILL_DIR__#${SKILL_DIR}#g" \
    -e "s#__INSTALL_DIR__#${INSTALL_DIR}#g" \
    "$UNIT_SRC" >"$TMP_UNIT"
$SUDO install -m 0644 "$TMP_UNIT" "$UNIT_DST"
rm -f "$TMP_UNIT"

$SUDO systemctl daemon-reload
$SUDO systemctl enable --now claude-state-agent.service

sleep 3
if $SUDO systemctl is-active --quiet claude-state-agent.service; then
    echo "✓ claude-state-agent actif sur http://127.0.0.1:18920 (bind=loopback par défaut)"
    echo "  Pour l'exposer sur le tailnet, édite $TOKEN_FILE et passe CLAUDE_FLEET_BIND=tailnet,"
    echo "  puis: $SUDO systemctl restart claude-state-agent"
else
    echo "✗ claude-state-agent n'a pas démarré — journalctl -u claude-state-agent -n 20" >&2
    exit 1
fi
